### ISSUE TITLE
[onboarding] SamirPS

### ISSUE THREAD

**Issue by SamirPS** [ubuntu-rocks/.github#6]
### 🚀 Introduction

Hi,

I'm Samir, a former member of the ROCKs team. I really like the ROCKs project and its associated tools, so I want to contribute to this project because it solves a lot of issues for the community :).

Regarding the repositories, I'm not sure for now because I want to focus more on helping people create and maintain ROCKs and also on doing some advocacy work for the project.

### 💬 Matrix username

@samirakarioh:ubuntu.com

### Canonical contributor licence agreement

- [X] I have read [Canonical's contributor licence agreement](https://ubuntu.com/legal/contributors)

### Ubuntu Code of Conduct

- [X] I have read [Ubuntu Code of Conduct](https://ubuntu.com/community/ethos/code-of-conduct)

**Comment by cjdcordeiro** [comment]
Hi @SamirPS ! Nice to have you :)

I see you are already a member of the Rocks Community space in Matrix.

I've sent an invite for you to become a contributor of this GH org. Once accepted, I'll close this issue and you'll let me know if you'd like to have repos for your community rocks.

**Comment by SamirPS** [comment]
Thank @cjdcordeiro :) 

I've just accepted it

**Comment by cjdcordeiro** [comment]
Cool. Let me know if you'd like one (or more) repos for your rocks
